# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "oss" {
    acl                 = "private"
    bucket              = "lilly-iac-tfstate-cn-shanghai"
    encrypt             = true
    key                 = "live/dev/cn-shanghai/./terraform.tfstate"
    region              = "cn-shanghai"
    tablestore_endpoint = "https://lilly-iac-tf.cn-shanghai.ots.aliyuncs.com"
    tablestore_table    = "lily_iac_tf_table"
  }
}
