locals {
  kms         = "kms"
  ram         = "ram"
  sls         = "sls"
  vpc_inputs  = "vpc_inputs"
  sg          = "sg"
  nacl        = "nacl"
  oss         = "oss"
  nas         = "nas"
  backup      = "backup"
  rds_pg      = "rds_pg"
  redis       = "redis"
  alb         = "alb"
  cdn         = "cdn"
  ecs         = "ecs"
  acs         = "acs"
  acr         = "acr"
  fc          = "fc"
  eventbridge = "eventbridge"
  mns         = "mns"
  dataworks   = "dataworks"
}
